debug: true
git:
    clone_dir: "./cache/"
    repo: "git@github.com:sdslabs/shogun-manifest-demo.git"
    branch: "main"
    polling_interval: 600
api:
    admin:
        email: "captainav0608@gmail.com"
        password: "password"
    port: 7007
    jwt:
        secret: "jwt-secret"
        expiration_hours: 1
