debug: true
data_dir: "/var/lib/shogun/" # Use absolute path
git:
    create_deploy_key: true
    repo: "git@github.com:sdslabs/shogun-manifest-demo.git"
    branch: "main"
    polling_interval: 5
api:
    admin:
        email: "captainav0608@gmail.com"
        password: "password"
    port: 7007
    jwt:
        secret: "jwt-secret"
        expiration_hours: 1
database:
    host: "127.0.0.1"
    port: 5432
    user: "shogun"
    password: "pwd"
    dbname: "shogun_db"
    ssl_mode: "disable"
    master_key: "qwertyuiop"
    encryption_salt: "salty-salt"
    